version: '3'

services:
  backend:
    restart: always
    expose:
      - 80:80
    networks:
      - app_network
    build:
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=api.framinar.com
      - LETSENCRYPT_HOST=api.framinar.com

networks:
  app_network:
    driver: bridge
